### ISSUE TITLE
Migrate this to ros-drivers

### ISSUE THREAD

**Issue by jihoonl** [ros-drivers/linux_peripheral_interfaces#1]
@tfoote @stonier 

`linux_utils` used to be a `linux_hardware` in turtlebot repository. But it can be more useful than staying only in turtlebot since it is for **linux**. Right now it provides laptop battery checker script.

Can we move this repo into ros-drivers?

**Comment by jack-oquin** [comment]
This looks like a useful message.

What is recommended for a "dumb" battery, where we only have a voltage measurement?
